---
- hosts: webservers
  vars:
  - warName: java-example.war
  - warRemotePath: /opt/tomcat/webapps

  tasks:
  - name: Copy WAR to Remote server
    copy: src=target/{{ warName }} dest={{ warRemotePath }}/{{ warName }} owner=tomcat group=tomcat
   
